import logging
from typing import Optional
import discord
from discord.ext import commands
from DiploGM.cogs.game_management import (adjudication,
                                          channel_management, chaos,
                                          deadline_management,
                                          game_creation,
                                          game_editing,
                                          grace)
from DiploGM import perms
from DiploGM.utils import send_message_and_file
from DiploGM.manager import Manager

logger = logging.getLogger(__name__)
manager = Manager()

class GameManagementCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(
        brief="Creates a new Diplomacy game.",
        description="Creates a Diplomacy game of the chosen variant and optionally version.",
    )
    @perms.gm_only("create a game")
    async def create_game(self, ctx: commands.Context) -> None:
        """Create a new game for the server.

        Usage: 
            `.create_game <gametype>`

        Note:
            Only one game per server can be created.
            Default for <gametype> is "classic".
            Variants are of the form <variant_name>.<variant_version>, e.g. "impdip.2.0".
            If a version is not provided, will default to the latest-numbered version.
            Available variants can be found by running .list_variants
        """
        await game_creation.create_game(ctx)

    @commands.command(brief="Exports the current game state as JSON")
    @perms.gm_only("export the game")
    async def export_game(self, ctx: commands.Context) -> None:
        """Exports the current game state (players, provinces, parameters) as a JSON file."""
        await game_creation.export_game(ctx)

    @commands.command(brief="Imports a game from a JSON file",
                      description="Imports a new game from an uploaded JSON file.")
    async def import_game(self, ctx: commands.Context) -> None:
        """Imports a game from an uploaded JSON file.

        Usage: 
            `.import_game`, attaching a JSON file ideally from `.export_game`

        Note:
            This command follows similar guidelines to .create_game
            The uploaded file is expected to be a JSON file generated by the bot, ideally from `.export_game`.
            You can modify the file before uploading, but do so at your own risk.
        """
        await game_creation.import_game(ctx)

    @commands.command(brief="Permanently deletes a game; cannot be undone")
    @perms.gm_only("delete the game")
    async def delete_game(self, ctx: commands.Context) -> None:
        """Completely deletes the game in the server. Cannot be undone.

        Usage:
            `.delete_game`

        Note:
            Cannot be undone!
        """
        await game_creation.delete_game(ctx)

    @commands.command(brief="lists all variants currently supported")
    @perms.gm_only("lists variants")
    async def list_variants(self, ctx: commands.Context) -> None:
        await game_creation.list_variants(ctx)

    @commands.command(brief="Archives a comms category")
    @perms.gm_only("archive the category")
    async def archive(self, ctx: commands.Context) -> None:
        """Set all channels within a category to read-only, during game close

        Usage: 
            Used as `.archive #<channel_mention>`

        Note: 
            Removes all permission overwrites and sets "send_messages" to false
            Does not apply to Administrator roles
        """
        await channel_management.archive(ctx)

    @commands.command(
        brief="Sets the current deadline",
        description="""Manages the deadline for the current phase.
        At the moment, this sets the default timestamp for the .ping_players command.
        In the future, this might have more functionality.
        """
    )
    @perms.gm_only("set deadline")
    async def set_deadline(self, ctx: commands.Context) -> None:
        """Manages the deadline for the current phase.

        Usage: 
            `.set_deadline <timestamp>`
            `.set_deadline adjust <relative time, e.g. 2 days, -3h, etc.>`
            `.set_deadline cancel`

        Note: 
            When orders are published, deadline is automatically advanced by 1-2 days depending on phase.
        """
        await deadline_management.set_deadline(ctx)

    @commands.command(
        brief="Pings players who don't have the expected number of orders.",
        description="""Pings all players in their orders channel that satisfy the following constraints:
        1. They have too many build orders, or too little or too many disband orders.
        2. They are missing move orders or retreat orders.
        You may also specify a timestamp to send a deadline to the players.
        * .ping_players <timestamp>
        """,
        aliases=["pp"]
    )
    @perms.gm_only("ping players")
    async def ping_players(self, ctx: commands.Context) -> None:
        """Pings all players with withstanding orders, listing number of needed orders and which units require them

        Usage: 
            `.ping_players <timestamp?>`

        Note: 
            Timestamp optional, will be formatted to "in XX hours" when displayed.
            If a deadline is set with .set_deadline, the timestamp will default to that time.
        """
        await deadline_management.ping_players(ctx)

    @commands.command(
        brief="Disables orders until .unlock_orders is run",
        description="""Disables orders until .enable_orders is run.
                 Note: Currently does not persist after the bot is restarted""",
        aliases=["lock"],
    )
    @perms.gm_only("lock orders")
    async def lock_orders(self, ctx: commands.Context) -> None:
        """Sets board flag to prevent new order submissions

        Usage: 
            `.lock_orders`
        """
        await adjudication.lock_orders(ctx)

    @commands.command(brief="Re-enables orders", aliases=["unlock"])
    @perms.gm_only("unlock orders")
    async def unlock_orders(self, ctx: commands.Context) -> None:
        """Sets board flag to enable new order submissions

        Usage: 
            `.unlock_orders`
        """
        await adjudication.unlock_orders(ctx)

    @commands.group(name="grace", brief="Manages graces", invoke_without_command=True)
    @perms.gm_only("handle graces")
    async def grace(self, ctx: commands.Context) -> None:
        """Command to log and view graces, which occur when adjudication is delayed due to a player missing orders.
        Use one of the following subcommands to manage graces:

        Usage: 
            `.grace log <user> <hours> <reason>`
            `.grace view user <user>`
            `.grace view server <server_id?>`
            `.grace delete <grace_id>`

        Note: 
            For more detailed information on each subcommand, use `.help grace <subcommand>`
        """
        await send_message_and_file(channel=ctx.channel, message="Valid commands are: *log*, *delete*, and *view*")

    @grace.command(name="log", brief="Logs a grace period", description="Usage: .grace <user> <hours> <reason>")
    @perms.gm_only("record a grace")
    async def grace_log(self,
                        ctx: commands.Context,
                        user: discord.User,
                        hours: float, *,
                        reason: str = "Unspecified") -> None:
        """Store a record of grace in a game, grace can be NMR or Extension and should be detailed in the reason

        Usage: 
            `.grace log     <user> <hours> <reason>`

        Note: 
            Can't log for bots
            Can log for any discord user

        Args:
            user (discord.User): User that has committed the grace
            hours (float): Time grace lasted/set to last
            reason (str): Why was the grace stored
        """
        await grace.grace_log(ctx, user, hours, reason)

    @grace.command(name="delete")
    @perms.gm_only("Delete a recorded grace")
    async def grace_delete(self, ctx: commands.Context, grace_id: int) -> None:
        """Delete a record of grace from the database

        Usage: 
            `.grace delete <grace_id>`

        Note: 
            Will return positive message even if no record for ID
            Use .grace view to find grace IDs

        Args:
            grace_id (int): Target Grace ID
        """
        await grace.grace_delete(ctx, grace_id)

    @grace.group(name="view", brief="Views grace records", invoke_without_command=True)
    async def grace_view(self, ctx: commands.Context) -> None:
        """Views grace records for a user or server

        Usage: 
            `.grace view user <user>`
            `.grace view server <server_id?>`

        Note:
            For more detailed information on each subcommand, use `.help grace view <subcommand>`
        """
        await send_message_and_file(channel=ctx.channel, message="Valid commands are: *user* and *server*")

    @grace_view.command(name="user", brief="View the grace history of a user")
    @perms.gm_only("view graces made by a user")
    async def grace_view_user(self, ctx: commands.Context, user: discord.User) -> None:
        """View the grace record for a specific user

        Usage: 
            `.grace view user <user>`

        Note: 
            Groups by server graces are logged in
            Records sorted by server_id (newer servers?) then creation datetime

        Args:
            user (discord.User): User to check
        """
        await grace.grace_view_user(ctx, user)

    @grace_view.command(name="server", brief="View the grace history of a server")
    @perms.gm_only("view graces that have occurred in a server")
    async def grace_view_server(self, ctx: commands.Context, server_id: Optional[int] = None) -> None:
        """View the grace record for the current server

        Usage: 
            `.grace view server <server_id?>`

        Note: 
            Groups by server graces are logged in
            Records sorted by server_id (newer servers?) then creation datetime

        Args:
            server_id (Optional[int], default=None): ID of the server to view
        """
        await grace.grace_view_server(ctx, server_id)

    @commands.command(
        brief="Publishes orders to #orders-log",
        description="For GM: Sends orders from previous phase to #orders-log",
    )
    @perms.gm_only("publish orders")
    async def publish_orders(self, ctx: commands.Context, *args) -> None:
        """Publishes orders to the orders log channel, uploads the map to the archive,
        and informs players about the phase change.
        
        Usage:
            `.publish_orders`
            `.publish_orders silent` - does not post in orders channels about phase changes
        
        Note:
            If a deadline is set, automatically updates the deadline by 1-2 days depending on phase.
            Posts in player channels information about the phase change unless "silent" is passed.
            If configured, also uploads the map to the archive.
        """
        await adjudication.publish_orders(ctx, *args)

    @commands.command(
        brief="Adjudicates the game",
        description="Adjudicates the game and uploads maps.",
        aliases=["adju", "adjudication"]
    )
    @perms.gm_only("adjudicate")
    async def adjudicate(self, ctx: commands.Context) -> None:
        """Adjudicates the game, and publishes the orders and results maps.
        
        Usage:
            `.adjudicate [arguments]`
        
        Args:
            `test`: Runs a test adjudication without touching the actual game state.
            `full`: Locks orders, adjudicates, uploads maps, publishes orders, and then unlocks orders.
            `<color_mode>`: Publishes maps with a specific color scheme.
            `confirm`: Adjudicates even if there are missing orders.
            `svg`: Uploads the maps as SVGs instead of PNGs.
        
        Note:
            By default, the command will not adjudicate if there are missing orders.
            Use the "confirm" argument to override this.
            Arguments can be combined as desired, so `.adjudicate full svg dark confirm` is valid.
            If `svg` and `full` are included, maps will still be uploaded as PNGs to the #maps channel.
            To undo an adjudication, use `.rollback`.
        """
        await adjudication.adjudicate(ctx)

    @commands.command(brief="Rolls back the game to the previous turn")
    @perms.gm_only("rollback")
    async def rollback(self, ctx: commands.Context) -> None:
        """Rolls back the game board to the previous phase

        Usage: 
            `.rollback`

        Note: 
            Will clear any orders in the current phase before rolling back.
        """
        await game_editing.rollback(ctx)

    @commands.command(brief="Reloads the current board with what is in the DB")
    @perms.gm_only("reload")
    async def reload(self, ctx: commands.Context) -> None:
        """Reloads the board state currently saved in the database.

        Usage: 
            `.reload`
        """
        await game_editing.reload(ctx)

    @commands.command(
        brief="Edits the game state and outputs the results map",
        description="""Edits the game state and outputs the results map.
        There must be one and only one command per line.
        Note: you cannot edit immalleable map state (eg. province adjacency).
        The following are the supported sub-commands:
        * set_phase {spring, fall, winter}_{moves, retreats, builds}
        * set_core <province_name> <player_name>
        * set_half_core <province_name> <player_name>
        * set_province_owner <province_name> <player_name>
        * create_unit {A, F} <player_name> <province_name>
        * create_dislodged_unit {A, F} <player_name> <province_name> <retreat_option1> <retreat_option2>...
        * delete_dislodged_unit <province_name>
        * delete_unit <province_name>
        * move_unit <province_name> <province_name>
        * transform_unit <new_unit_type> <province_name>
        * dislodge_unit <province_name> <retreat_option1> <retreat_option2>...
        * make_units_claim_provinces {True|(False) - whether or not to claim SCs}
        * set_player_points <player_name> <integer>
        * set_player_vassal <liege> <vassal>
        * remove_relationship <player1> <player2>
        * load_state <server_id> <spring, fall, winter}_{moves, retreats, builds> <year>
        * apocalypse {all OR army, fleet, core, province} !!! deletes everything specified !!!
        * bulk <command> {<player_name> | nothing if you're using delete_units} <list_of_province_names> {use with commands like set_total_owner to use it repeatedly}
        * bulk transform_unit <new_unit_type> <list_of_province_names>
        * bulk_create_units <player_name> {A, F} <list_of_province_names>
        """,
    )
    @perms.gm_only("edit")
    async def edit(self, ctx: commands.Context) -> None:
        """Edits the current board state

        Usage: 
            `.edit <commands>`
        """
        await game_editing.edit(ctx)

    @commands.command(
        brief="Blitz game channel creation",
        description="Creates all possible channels between two players for blitz in available comms channels.",
    )
    @perms.gm_only("create blitz comms channels")
    async def blitz(self, ctx: commands.Context) -> None:
        """Creates all pairwise press channels between players in a game

        Usage: 
            `.blitz`

        Note: 
            Uses the board.get_players() method (which is read from the config)
        """
        await channel_management.blitz(ctx)

    @commands.command(brief="Gets player activity",
                      description="""Gets the last time each player sent a message.""")
    @perms.gm_only("get last message times")
    async def last_message(self, ctx: commands.Context) -> None:
        """Gets the last time each player sent a message.

        Usage: 
            `.last_message`

        Note: 
            This data does not persist across bot restarts.
            Does not differentiate between orders, press, or other messages.
        """
        await channel_management.last_message(ctx)

    @commands.command(brief="Publicize void for chaos",
                      hidden=True)
    async def publicize(self, ctx: commands.Context) -> None:
        """Opens a channel (usually a void) to the spectator role

        Usage: 
            Used as `.publicize`

        Note: 
            Used exclusively for the World of Chaos event

        Args:
            ctx (commands.Context): Context from discord regarding command invocation

        Returns:
            None

        Raises:
            None:
            Messages:
                You are not a GM
                This is not a chaos game
                Could not find applicable user
        """
        await chaos.publicize(ctx)

    @commands.command(
        brief="Edits game parameters",
        description="""Modifies a game parameter to a certain value.
        There must be one and only one command per line.
        Note: you cannot edit immalleable map state (eg. province adjacency).
        The following are the supported parameters and possible values:
        * game_name <game_name>
        * building ['classic', 'cores', 'control', 'anywhere']
        * convoyable_islands ['disabled', 'enabled']
        * supportable_cores ['disabled', 'enabled']
        * transformation ['disabled', 'moves', 'builds', 'all']
        * dp ['disabled', 'enabled']
        * victory_conditions ['classic', 'vscc']
        * victory_count [number] (only used with classic victory conditions)
        * iscc [player] [starting scs]
        * vscc [player] [victory scs] (only used with vscc victory conditions)
        * capital [player] [province]
        * player_name [original name] [new name]
        * player_color [player_name] [hex_code]
        * hide_player [player] ['true', 'false']
        * add_player [player] [color] (Once added, a player cannot be removed)
        """,
    )
    @perms.gm_only("edit game")
    async def edit_game(self, ctx: commands.Context) -> None:
        """Edits game parameters.

        Usage: 
            `.edit_game <commands>`
        """
        await game_editing.edit_game(ctx)

    @commands.command(brief="Renames a player",
                      description="Renames a player, and updates their role and channel names")
    @perms.gm_only("rename player")
    async def rename_player(self, ctx: commands.Context, old_name: str, new_name: str) -> None:
        """Renames a player, and updates their role and channel names if possible.

        Usage: 
            `.rename_player <old_name> <new_name>`

        Note:
            To include a space in a name, surround the name with quotes.
            You cannot rename a player to have the same name as another existing player.
        """
        await game_editing.rename_player(ctx, old_name, new_name)

async def setup(bot):
    cog = GameManagementCog(bot)
    await bot.add_cog(cog)
