ALTER TABLE boards ADD COLUMN phase_index INTEGER DEFAULT 0;
ALTER TABLE provinces ADD COLUMN phase_index INTEGER DEFAULT 0;
ALTER TABLE retreat_options ADD COLUMN phase_index INTEGER DEFAULT 0;
ALTER TABLE units ADD COLUMN phase_index INTEGER DEFAULT 0;
ALTER TABLE builds ADD COLUMN phase_index INTEGER DEFAULT 0;
ALTER TABLE dp_orders ADD COLUMN phase_index INTEGER DEFAULT 0;