name = "Era of Solitude"
file = "eraofsolitude.b1.svg"
year = 1167
build_options = "cores"
victory_conditions = "classic"
victory_count = 20
convoyable_islands = "enabled"
expected_loops = 2

['svg config']
detect_starting_units = true
unit_type_labeled = false
unit_labels = true
province_labels = true
center_labels = true
default_sea_color = "18638f"
border_margin_hint = 5
map_width = 6000
unit_radius = 32
order_stroke_width = 5
neutral = "808080"
neutral_sc = "ffffff"
loc_x_offset = 24.957
loc_y_offset = 22.6035
delete_layer = ["army", "retreat_army", "fleet", "retreat_fleet"]

scoreboard.sort = true
scoreboard.indexes.1 = "__name__"
scoreboard.indexes.2 = "__score__"

season_format.0 = "%Z"
season_format.1 = "%Y"

[overrides.provinces]
OS1.unit_loc = [5725.924, 810.390]
OS1.retreat_unit_loc = [5773.933, 832.453]
OS2.unit_loc = [5725.924, 1489.213]
OS2.retreat_unit_loc = [5773.933, 1511.275]
OS3.unit_loc = [5725.924, 2187.834]
OS3.retreat_unit_loc = [5773.933, 2209.897]

[overrides.provinces.Arak]
adjacencies = ["Nightstream Sea"]

[overrides.provinces.'Nightstream Sea']
adjacencies = ["Arak"]

[overrides.provinces.'Western Frostlands'.coasts]
nc = ["Karanak", "Mevan Bay", "Kharbranth"]
sc = ["Kharbranth", "Sea of Kharbranth", "Longbrow's Straits", "Thla"]

[overrides.provinces.'Iriali Highlands'.coasts]
wc = ["Kasitor", "Iriali Coast", "Rall Elorim"]
ec = ["Rall Elorim", "Western Reshi Sea", "Iriali Lowlands"]

[players.Alethkar]
color = "23436d"
iscc = 4

[players.Azir]
color = "c9aa58"
iscc = 3

[players.Iri]
color = "e09c4e"
iscc = 3

[players.'Jah Keved']
color = "b0a4d1"
iscc = 4

[players.Listeners]
color = "404040"
iscc = 3

[players.Marat]
color = "4e9038"
iscc = 3

[players.Shinovar]
color = "692a33"
iscc = 3

[players.Thaylenah]
color = "895d50"
iscc = 3

[players.Tukar]
color = "b56750"
iscc = 3

[players.Yulay]
color = "58a89f"
iscc = 3
