_WS: /[ \t]+/

order: (move_order
      | hold_order
      | support_order
      | convoy_order
      | core_order
      | transform_order
      | dp_order) _WS

retreat: (retreat_order
       | disband_order
	| non_retreat_order) _WS

build: ( build_unit
       | disband_unit
       | transform_unit
	| waive_order
       | non_build_order) _WS

move_order: unit _WS MOVE _WS province

hold_order: unit _WS HOLD

l_move_order: l_unit _WS MOVE _WS province

l_hold_order: l_unit _WS HOLD

support_order: unit _WS ((SUPPORT _WS (l_move_order | l_hold_order)) | ((SUPPORT_HOLD | SUPPORT) _WS l_unit))

convoy_order: unit _WS CONVOY _WS l_move_order

core_order: unit _WS CORE

transform_order: unit _WS TRANSFORM (_WS COAST)?

dp_order: DP _WS NUMBER _WS (move_order
                           | hold_order
                           | support_order
                           | convoy_order
                           | transform_order)

retreat_order: retreat_unit _WS RETREAT _WS province

disband_order: ( retreat_unit _WS DISBAND ) | ( DISBAND _WS retreat_unit )

non_retreat_order: (support_order | convoy_order | core_order | transform_order | build_unit | waive_order )

disband_unit: ( unit _WS DISBAND ) | ( DISBAND _WS unit )

build_unit: ( BUILD _WS DESCRIPTOR province ) | ( BUILD _WS province _WS DESCRIPTOR )

transform_unit: (unit _WS TRANSFORM (_WS COAST)?) | (TRANSFORM _WS unit (_WS COAST)?)

waive_order: ( WAIVE _WS NUMBER )

non_build_order: (move_order | hold_order | support_order | convoy_order | core_order)

SUPPORT_HOLD.3 : /(support|supports|s)[ \-_]?(hold|holds|h|stand|stands)/i

DEFECT.2 : "defect"

HOLD.2 : "h"
       | "hold"
       | "holds"
       | "stand"
       | "stands"

MOVE.2 : "-"
       | "–"
       | "−"
       | "->"
       | "–>"
       | "−>"
       | "to"
       | "m"
       | "move"
       | "moves"
       | "moves to"
       | "into"

SUPPORT.2 : "s"
        | "support"
        | "supports"

CONVOY.2 : "c"
        | "convoy"
        | "convoys"

CORE.2 : "core"
       | "cores"

TRANSFORM.2 : "transform"
            | "transforms"
            | "converts"
            | "t"

DP.2 : "dp"
     | "diplomany points"

RETREAT.2 : MOVE
          | "r"
          | "retreat"
          | "retreats"

DISBAND.2 : "d"
          | "disband"
          | "disbands"
          | "boom"
          | "explodes"
          | "dies"
          | "drop"
          | "drops"
          | "remove"

BUILD.2 : "b"
        | "build"
        | "place"

WAIVE.2: "w"
       | "waive"

NUMBER : /[0-9]{1,3}(:?)/

unit : (DESCRIPTOR)? province

l_unit : (DESCRIPTOR)? province

retreat_unit : (DESCRIPTOR)? province

DESCRIPTOR.2 : /{{UNIT_TYPE_STRINGS}}/i _WS

province : PROVINCE (_WS PROVINCE) ~ 0..3

PROVINCE : /(?![{{UNIT_TYPE_CODES}}]\s)[a-zA-Z0-9\._‘’`´′‛'-]+(?=\s)/

COAST.2: /[a-z]c/i
